INSERT INTO WEATHER_STATUS VALUES ( 1, 'Delhi' ,0,0)
INSERT INTO WEATHER_STATUS VALUES ( 2, 'Pune' ,0,0)
INSERT INTO WEATHER_STATUS VALUES ( 3, 'Bangalore' ,0,0)
INSERT INTO WEATHER_STATUS VALUES ( 4, 'Hyderabad' ,0,0)